version: "3.8"

services:
  app:
    build: .
    depends_on:
      - db
    ports:
      - "8000:8000"
    env_file:
      - ./.env
    volumes:
      - ./:/usr/src/app:ro
    command: bash -c "alembic upgrade head && uvicorn src.main:app --host 0.0.0.0 --port 8000 --reload"

  db:
    image: postgres:15-bullseye
    restart: always
    env_file:
      - ./.env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
